import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "./store/provider";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{/* <Provider store={store}> */}
				<Providers>
					<Header />
					<div className=" bg-background">
						<Suspense fallback={<Loading />}>{children}</Suspense>
					</div>
					<Toaster />
					<Footer />
				</Providers>

				{/* </Provider> */}
			</body>
		</html>
	);
}
