import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import { NextUIProvider } from "@nextui-org/react";
import Footer from "@/components/Footer/Footer";
import store from "@/store/store";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{/* <Provider store={store}> */}
				<Header />
				{children}

				<Footer />
				{/* </Provider> */}
			</body>
		</html>
	);
}
